import { describe, it, expect } from 'vitest';
import { mkdtempSync, existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generate } from '../src/generate.js';

const fixture = fileURLToPath(new URL('./fixtures/small.dbml', import.meta.url));
const overlays = fileURLToPath(new URL('./fixtures/overlays/', import.meta.url));

describe('generate', () => {
  it('writes index + tables/ + domains/ tree', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    const res = generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    expect(existsSync(join(out, '_index.md'))).toBe(true);
    expect(existsSync(join(out, 'tables', 'orders.md'))).toBe(true);
    expect(existsSync(join(out, 'domains', 'commerce.md'))).toBe(true);
    expect(res.issues).toEqual([]);
    expect(readFileSync(join(out, '_index.md'), 'utf8')).toContain('audit_log');
  });

  it('refuses to write outside outDir for a path-traversal table name', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    const maliciousDbml = join(out, 'malicious.dbml');
    writeFileSync(maliciousDbml, 'Table "../../../../tmp/pwned" {\n  id int [pk]\n}\n');
    expect(() => generate({ input: maliciousDbml, outDir: out, linkStyle: 'md' })).toThrow(/pwned/);
    expect(existsSync('/tmp/pwned.md')).toBe(false);
  });

  it('writes AGENTS.md into the output dir root with interpolated stats', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    const agentsPath = join(out, 'AGENTS.md');
    expect(existsSync(agentsPath)).toBe(true);
    const md = readFileSync(agentsPath, 'utf8');
    expect(md).toContain('5 tables · 3 domains');
    expect(md).toContain('identity');
    expect(md).toContain('Commerce');
  });

  it('overwrites an existing AGENTS.md', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    writeFileSync(join(out, 'AGENTS.md'), 'stale content from a previous run');
    generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    const md = readFileSync(join(out, 'AGENTS.md'), 'utf8');
    expect(md).not.toContain('stale content from a previous run');
    expect(md).toContain('# AGENTS.md');
  });
  it('prunes a stale domain file the run did not write', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    // simulate a TableGroup rename: last run's domain file survives on disk
    const orphan = join(out, 'domains', 'legacy-reporting.md');
    writeFileSync(orphan, '# Domain: stale\n');
    expect(existsSync(orphan)).toBe(true);

    const res = generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    expect(existsSync(orphan)).toBe(false);
    expect(res.pruned).toContain(join('domains', 'legacy-reporting.md'));
    // the live files are untouched
    expect(existsSync(join(out, 'domains', 'commerce.md'))).toBe(true);
    expect(existsSync(join(out, 'tables', 'orders.md'))).toBe(true);
  });

  it('prunes a stale table file the run did not write', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    const orphan = join(out, 'tables', 'dropped_table.md');
    writeFileSync(orphan, '# dropped\n');

    const res = generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    expect(existsSync(orphan)).toBe(false);
    expect(res.pruned).toContain(join('tables', 'dropped_table.md'));
  });

  it('never prunes the output root, where export.jsonl lives', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    const exportFile = join(out, 'export.jsonl');
    writeFileSync(exportFile, '{"table":"orders"}\n');
    const res = generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    expect(existsSync(exportFile)).toBe(true);
    expect(readFileSync(exportFile, 'utf8')).toContain('orders');
    expect(res.pruned).toEqual([]);
  });

  it('leaves non-markdown files in generated dirs alone', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    mkdirSync(join(out, 'tables'), { recursive: true });
    const keep = join(out, 'tables', 'notes.txt');
    writeFileSync(keep, 'not generated by this tool');
    generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    expect(existsSync(keep)).toBe(true);
  });

  it('keeps stale files when prune is disabled', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    const orphan = join(out, 'domains', 'legacy-reporting.md');
    writeFileSync(orphan, '# Domain: stale\n');

    const res = generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md', prune: false });
    expect(existsSync(orphan)).toBe(true);
    expect(res.pruned).toEqual([]);
  });

  it('reports nothing pruned on a clean regenerate', () => {
    const out = mkdtempSync(join(tmpdir(), 'dbmlgraph-'));
    generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    const res = generate({ input: fixture, overlaysDir: overlays, outDir: out, linkStyle: 'md' });
    expect(res.pruned).toEqual([]);
  });
});
